# This is a file for you to write an un-named mutation. 
# Only one un-named mutation is allowed per file.
mutation {
  user_insert(data: {clerkId: "user_3DdVabsBHnckJasrZMHWCyp09go", email: "ghostrex2@gmail.com", imageUrl: "https://img.clerk.com/eyJ0eXBlIjoicHJveHkiLCJzcmMiOiJodHRwczovL2ltYWdlcy5jbGVyay5kZXYvb2F1dGhfZ29vZ2xlL2ltZ18zRGRWYVl2eDN4dlRnNDVCS1R2VnFqcHExVVIifQ", username: "fitiavana"})
}